name: Automacao 1

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: beta
        id: setup-chrome
      - run: |
          echo Installed chromium version: ${{ steps.setup-chrome.outputs.chrome-version }}
          ${{ steps.setup-chrome.outputs.chrome-path }} --version

      - run: chrome --version

      - name: Build with Maven
        env:
          GH_TOKEN: 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
        run: |
          mvn clean test -Dgithub.token=$GH_TOKEN

      # - name: Generate Allure Report
      #   run: mvn allure:report

        
      # - name: Publish Allure Results
      #   uses: allure-actions/upload@v2
      #   with:
      #     resultsDirectory: allure-results

      # - name: Upload Artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: allure-report
      #     path: target/site/allure-maven-plugin

      - name: Cleanup
        run: mvn clean
